Fox Gnome Human Interface library (foxGHI)  08/09/2022 
============================================================

GENERAL INFO:
================


Preklad a instalace.
========================
Zavislosti:
  Foxtoolkit 1.7.76 - GUI Famework http://fox-toolkit.org/ftp/fox-1.7.76.tar.gz

Zavislosti pro kompilaci  
  cmake >= 3.10
  
Po stazeni projektu z Githubu (a pripadnem rozbaleni) prejdete do slozky s projektem a zadejte nasledujici 
sekvenci prikazu:
  mkdir build
  cd build && cmake .. 
  make
  sudo make install
  
Po uspesne kompilaci a sestaveni projektu bude vysledna knihovna a hlavickove soubory nainstalovana do 
adresare /opt/foxGHI/0.1/1/  

Autor a Licence
===================
Pavel Šafařík <drakarax@seznam.cz>

Tento soubor je součástí Morfeus.
Morfeus je svobodný software: můžete jej redistribuovat a/nebo upravovat za podmínek GNU General Public License, jak byla zveřejněna Free Software Foundation, buď verze 3 licence, nebo (dle vašeho uvážení) jakékoli pozdější verze.
Morfeus je distribuován v naději, že bude užitečný, ale BEZ JAKÉKOLI ZÁRUKY; dokonce bez předpokládané záruky PRODEJNOSTI nebo VHODNOSTI PRO KONKRÉTNÍ ÚČEL. Další podrobnosti najdete v GNU General Public License.
Spolu s Morfeus byste měli obdržet kopii GNU General Public License. Pokud ne, podívejte se na <https://www.gnu.org/licenses/>.

=== KONEC ===

